//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace peeweeptech.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class Kod
    {
        public Kod()
        {
            this.Yorum = new HashSet<Yorum>();
            this.Etiket = new HashSet<Etiket>();
        }
    
        public int kod_id { get; set; }
        public string baslik { get; set; }
        [UIHint("tinymce_full_compressed"),AllowHtml]
        public string icerik { get; set; }
        public string foto { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<int> kategori_id { get; set; }
        public Nullable<int> üye_id { get; set; }
        public Nullable<int> okunma { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Uye Uye { get; set; }
        public virtual ICollection<Yorum> Yorum { get; set; }
        public virtual ICollection<Etiket> Etiket { get; set; }
    }
}
