//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace peeweeptech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uye
    {
        public Uye()
        {
            this.Kod = new HashSet<Kod>();
            this.Yorum = new HashSet<Yorum>();
        }
    
        public int üye_id { get; set; }
        public string kullanici_adi { get; set; }
        public string email { get; set; }
        public string şifre { get; set; }
        public string AdSoyad { get; set; }
        public string foto { get; set; }
        public Nullable<int> yetki_id { get; set; }
    
        public virtual ICollection<Kod> Kod { get; set; }
        public virtual Yetki Yetki { get; set; }
        public virtual ICollection<Yorum> Yorum { get; set; }
    }
}
