//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace peeweeptech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum
    {
        public int yorum_id { get; set; }
        public string icerik { get; set; }
        public Nullable<int> üye_id { get; set; }
        public Nullable<int> kod_id { get; set; }
        public string tarih { get; set; }
    
        public virtual Kod Kod { get; set; }
        public virtual Uye Uye { get; set; }
    }
}
